# Comparison

| n | SageMath | python  | numpy   | cython  | cython+numpy | C (print) |
| - | -------- | ------  | -----   | ------  | ------------ | --------- |
| 4 | 482 µs   | 30.2 µs | 163 µs  | 14.3 µs | 125 µs       | 33.9 µs   |
| 5 | 1.69 ms  | 124 µs  | 708 µs  | 58.5 µs | 557 µs       | 37.8 µs   |
| 6 | 6.33 ms  | 504 µs  | 2.98 ms | 236 µs  | 2.46 ms      | 53.5 µs   |
| 7 | 23.4 ms  | 2.05 ms | 12.6 ms | 966 µs  | 10.7 ms      | 115 µs    |
| 8 | 90 ms    | 8.16 ms | 54.6 ms | 3.92 ms | 45.4 ms      | 358 µs    |
| 9 |          | 33.3 ms |         |         |              | 1.41 ms   |

# SageMath: `IntegerListsLex`

In [1]:
reset()

In [2]:
def go(n):
    X = IntegerListsLex(n, length=n).list()

In [3]:
%%timeit
go(4)

492 µs ± 2.51 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [4]:
%%timeit
go(5)

1.79 ms ± 44.8 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [5]:
%%timeit
go(6)

6.52 ms ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [6]:
%%timeit
go(7)

24.4 ms ± 155 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [7]:
%%timeit
go(8)

92.9 ms ± 950 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# python

In [8]:
reset()

In [9]:
cd python

/Users/saliola/git-repos/nonnegative_integer_matrices/python


In [10]:
%run nonneg_int_matrices.py

[[0, 3], [0, 1], [5, 0]]
[[0, 3], [1, 0], [4, 1]]
[[1, 2], [0, 1], [4, 1]]
[[1, 2], [1, 0], [3, 2]]
[[2, 1], [0, 1], [3, 2]]
[[2, 1], [1, 0], [2, 3]]
[[3, 0], [0, 1], [2, 3]]
[[3, 0], [1, 0], [1, 4]]


In [13]:
def go(n):
    X = list(nonneg_int_vectors_iter(n, [n] * n))

In [14]:
%%timeit
go(4)

30.3 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [15]:
%%timeit
go(5)

125 µs ± 437 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [16]:
%%timeit
go(6)

511 µs ± 3.1 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [17]:
%%timeit
go(7)

2.06 ms ± 6.87 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [18]:
%%timeit
go(8)

8.27 ms ± 58.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [19]:
%%timeit
go(9)

33.3 ms ± 303 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# numpy

In [20]:
reset()

In [21]:
cd ../numpy/

/Users/saliola/git-repos/nonnegative_integer_matrices/numpy


In [22]:
%run nonneg_int_matrices.py

[[0 3]
 [0 1]
 [5 0]]
[[0 3]
 [1 0]
 [4 1]]
[[1 2]
 [0 1]
 [4 1]]
[[1 2]
 [1 0]
 [3 2]]
[[2 1]
 [0 1]
 [3 2]]
[[2 1]
 [1 0]
 [2 3]]
[[3 0]
 [0 1]
 [2 3]]
[[3 0]
 [1 0]
 [1 4]]


In [23]:
def go(n):
    X = list(nonneg_int_vectors_iter(n, [n] * n))

In [24]:
%%timeit
go(4)

168 µs ± 2.35 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [25]:
%%timeit
go(5)

718 µs ± 5.39 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [26]:
%%timeit
go(6)

3.09 ms ± 33.5 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [27]:
%%timeit
go(7)

12.9 ms ± 56.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [28]:
%%timeit
go(8)

54.6 ms ± 285 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# cython

In [29]:
reset()

In [30]:
cd ../cython

/Users/saliola/git-repos/nonnegative_integer_matrices/cython


In [31]:
%%bash
sage --python setup.py build_ext --inplace

Compiling nonneg_int_matrices.pyx because it changed.
[1/1] Cythonizing nonneg_int_matrices.pyx
running build_ext
building 'nonneg_int_matrices' extension
creating build
creating build/temp.macosx-10.9-universal2-cpython-39
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -iwithsysroot/System/Library/Frameworks/System.framework/PrivateHeaders -iwithsysroot/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/Headers -Werror=implicit-function-declaration -Wno-error=unreachable-code -I/Users/saliola/Applications/sage-10.5/local/var/lib/sage/venv-python3.9/include -I/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.9/include/python3.9 -c nonneg_int_matrices.c -o build/temp.macosx-10.9-universal2-cpython-39/nonneg_int_matrices.o


nonneg_int_matrices.c:5508:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
 5508 |                     CYTHON_FALLTHROUGH;
      |                     ^
nonneg_int_matrices.c:556:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
  556 |       #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
      |                                  ^
nonneg_int_matrices.c:5519:21: warning: fallthrough annotation in unreachable code [-Wunreachable-code-fallthrough]
 5519 |                     CYTHON_FALLTHROUGH;
      |                     ^
nonneg_int_matrices.c:556:34: note: expanded from macro 'CYTHON_FALLTHROUGH'
  556 |       #define CYTHON_FALLTHROUGH __attribute__((fallthrough))
      |                                  ^
nonneg_int_matrices.c:6510:26: warning: code will never be executed [-Wunreachable-code]
 6510 |                 module = PyImport_ImportModuleLevelObject(
      |                          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
3 warnings

creating build/lib.macosx-10.9-universal2-cpython-39
gcc -bundle -undefined dynamic_lookup -Wl,-headerpad,0x1000 -L/Users/saliola/Applications/sage-10.5/local/lib build/temp.macosx-10.9-universal2-cpython-39/nonneg_int_matrices.o -o build/lib.macosx-10.9-universal2-cpython-39/nonneg_int_matrices.cpython-39-darwin.so
copying build/lib.macosx-10.9-universal2-cpython-39/nonneg_int_matrices.cpython-39-darwin.so -> 


In [32]:
from nonneg_int_matrices import nonneg_int_vectors_iter

In [33]:
def go(n):
    X = list(nonneg_int_vectors_iter(n, [n] * n))

In [34]:
%%timeit
go(4)

14.5 µs ± 197 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


In [35]:
%%timeit
go(5)

58.2 µs ± 689 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [36]:
%%timeit
go(6)

235 µs ± 1.79 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [37]:
%%timeit
go(7)

954 µs ± 5.84 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [38]:
%%timeit
go(8)

3.9 ms ± 44.9 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


# cython + numpy

In [1]:
reset()

In [4]:
cd ../cython-with-numpy

/Users/saliola/git-repos/nonnegative_integer_matrices/cython-with-numpy


In [5]:
%%bash
sage --python setup.py build_ext --inplace

running build_ext
copying build/lib.macosx-10.9-universal2-cpython-39/nonneg_int_matrices.cpython-39-darwin.so -> 


In [6]:
from nonneg_int_matrices import nonneg_int_vectors_iter
import numpy as np

In [7]:
def go(n):
    X = list(nonneg_int_vectors_iter(n, np.array([n] * n)))

In [8]:
%%timeit
go(4)

125 µs ± 1.12 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [9]:
%%timeit
go(5)

570 µs ± 7.33 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [10]:
%%timeit
go(6)

2.5 ms ± 41.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [11]:
%%timeit
go(7)

10.7 ms ± 87.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [12]:
%%timeit
go(8)

45.9 ms ± 524 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


# C

In [13]:
reset()

In [14]:
cd ../c-python-wrapper

/Users/saliola/git-repos/nonnegative_integer_matrices/c-python-wrapper


In [15]:
%%bash
make python-wrapper

gcc -fPIC -shared -o nonneg_int_vectors.so nonneg_int_vectors.c


In [16]:
from nonneg_int_vectors_wrapper import print_nonneg_int_vectors

In [17]:
def go(n):
    print_nonneg_int_vectors(n, [n] * n)

In [19]:
%timeit go(4)

33.3 µs ± 308 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [20]:
%timeit go(5)

37.8 µs ± 454 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [21]:
%timeit go(6)

52.9 µs ± 229 ns per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [22]:
%timeit go(7)

115 µs ± 1.21 µs per loop (mean ± std. dev. of 7 runs, 10,000 loops each)


In [23]:
%timeit go(8)

356 µs ± 2.09 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [24]:
%timeit go(9)

1.39 ms ± 65.2 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
